# Generated by Django 3.0.7 on 2020-11-29 12:06

# import django.contrib.postgres.fields.jsonb
from django_mysql.models import JSONField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='solutionResult',
            field=models.CharField(max_length=100, null=True, verbose_name='运行结果'),
        ),
        migrations.AddField(
            model_name='solution',
            name='userId',
            field=models.CharField(default='1', max_length=20, verbose_name='所属用户id'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_measurement',
            field=models.CharField(max_length=100, null=True, verbose_name='评价指标'),
        ),
        migrations.AlterField(
            model_name='dict',
            name='other',
            field=JSONField(blank=True, null=True, verbose_name='其它信息'),
        ),
        migrations.AlterField(
            model_name='historicaldict',
            name='other',
            field=JSONField(blank=True, null=True, verbose_name='其它信息'),
        ),
    ]
