# Generated by Django 3.0.7 on 2020-11-29 12:11

#import django.contrib.postgres.fields.jsonb
from django_mysql.models import JSONField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20201129_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict',
            name='other',
            field=JSONField(blank=True, null=True, verbose_name='其它信息'),
        ),
        migrations.AlterField(
            model_name='historicaldict',
            name='other',
            field=JSONField(blank=True, null=True, verbose_name='其它信息'),
        ),
    ]
