# Generated by Django 3.0.7 on 2020-11-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20201129_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalDict',
        ),
    ]
