# Generated by Django 3.0.7 on 2020-12-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_type_measument',
            old_name='dataset_id',
            new_name='measurement_id',
        ),
    ]
