# Generated by Django 3.0.7 on 2021-04-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20210105_1918'),
        ('system', '0002_file_belong_dept'),
    ]

    operations = [
    ]
